### ISSUE TITLE
making AMQP connection in every HTTP request

### ISSUE THREAD

**Issue by hamidreza-s** [s-noroozi-cs/LogServiceQueue#1]
Making AMQP connection in every HTTP request has a big performance disadvantage.
Link: https://github.com/s-noroozi-cs/LogServiceQueue/blob/master/src/lsq_service.erl#L40

**Comment by s-noroozi-cs** [comment]
Thanks a lot for your code review and comment.
Temporary I use pg2 to reuse resource (AMQP connection and channel).
In current changes, I do not close connection and channel.
According as technical document channel must be closed but using pooling to reuse connection.
At next free time try to load test and finalize this section.

**Comment by hamidreza-s** [comment]
Hi Saeed, Welcome.

Using thread pools can be a thing, but erlang/otp can have more natural solutions.
- A simple one is passing the AMQP connection through lsq_service. As lsq_service is a long lived process that are being supervised, so it can have State (in other word; Context). This way you must make your connection in its init/1 hook, then using it in every hooks of lsq_service as State. 
- Another natural solution is implementing a gen_server that has an AMQP connection in its state, so you can pass your logs to it with message passing and that gen_server handles publishing logs to channel. This way you can have multiple connections and let a supervisor to supervise them. So you separate your concerns and more importantly; the fault in your connections doesn't apply on your HTTP handler and vice versa. 

Thanks.

**Comment by s-noroozi-cs** [comment]
Hi Hamidreza

I choose second option. I'm trying to apply a gen_server solution and it's work.
Response text has tiny Improvement.

Thanks again for your hint and direction.

**Comment by hamidreza-s** [comment]
Very well,

You know, "crash" is a common behavior of erlang processes. What if your logserver crashes? It really needs to be supervised by your lsq_sup or a new one.

**Comment by s-noroozi-cs** [comment]
You right again and pointed to a good thing.
Fix this problem and commit related changes.

For fun:
When I was reading technical document for "Supervision Principles" see fun thing on "one_for_one" and "one_for_all" subjects.
In military period listened thing like this,  more and more , "eulogy for one (nobody) and punishment  for all"

**Comment by hamidreza-s** [comment]
That makes sense now.
Fortunately I didn't experience military service period. Seems that I missed a lot of fun :D
